name: housekeeper_v1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.22.0
  firebase_database: ^10.2.4
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  shared_preferences: ^2.0.13
  flutter_riverpod: ^2.3.6
  get: ^4.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.24.1
  mockito: ^5.0.8
  build_runner: ^2.0.4


flutter:
  uses-material-design: true
