// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_kVH6MB_BZj5O0JgD-jijOWelu43gcI4',
    appId: '1:477401788196:web:668b27672526b80d27cdb1',
    messagingSenderId: '477401788196',
    projectId: 'housekeeper-62e8d',
    authDomain: 'housekeeper-62e8d.firebaseapp.com',
    storageBucket: 'housekeeper-62e8d.appspot.com',
    measurementId: 'G-G2L0EWGTNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbBomxGkWuFJo5vE4Klp7Kuwmaaj82mk',
    appId: '1:477401788196:android:a926da8a2d161a4027cdb1',
    messagingSenderId: '477401788196',
    projectId: 'housekeeper-62e8d',
    storageBucket: 'housekeeper-62e8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcBfWhKvM6j1GCFmPQ1oXBwRvvIfmQLfI',
    appId: '1:477401788196:ios:799b177fc7e6dcac27cdb1',
    messagingSenderId: '477401788196',
    projectId: 'housekeeper-62e8d',
    storageBucket: 'housekeeper-62e8d.appspot.com',
    iosClientId: '477401788196-qn0020qd17jis5eod4gc8ihottueuetc.apps.googleusercontent.com',
    iosBundleId: 'com.example.housekeeperV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcBfWhKvM6j1GCFmPQ1oXBwRvvIfmQLfI',
    appId: '1:477401788196:ios:45b3a6a046b6190927cdb1',
    messagingSenderId: '477401788196',
    projectId: 'housekeeper-62e8d',
    storageBucket: 'housekeeper-62e8d.appspot.com',
    iosClientId: '477401788196-8nqeautel0vgaa8pjg2na6futtftfp0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.housekeeperV1.RunnerTests',
  );
}
